### ISSUE TITLE
Css issue whe draggin from a structure

### ISSUE THREAD

**Issue by CaptainMad** [vishalok12/jquery-dragarrange#2]
Hi there
Using the dragarrange plugin, I notice a problem when the div element-container is in a table structure.
see the effect here : http://www.fcpartner.com/demo_drag.html
I guess the proble is in the line 195 :       position: 'absolute',

Looking forward reading from you guys :!

**Comment by vishalok12** [comment]
Hi CaptainMad,
First, thanks for notifying the issue.
I will look for the issue in weekend. If you have already fixed it, i will be more happy to merge your pull request :-)

**Comment by CaptainMad** [comment]
Unfortunately I haven't fixed it yet but tested several tricks without success.
Quick hint : on Chrome, using F12 facilities, if you unselect the Position : Absolute of the moving div, you get strange behavour of the moving div ...  good luck !

**Comment by vishalok12** [comment]
@CaptainMad It seems to be an issue. For the time being, you can fix it by assigning parent element with style as "position: relative". That will solve the issue.

**Comment by CaptainMad** [comment]
Thanks
Works fine putting "position: relative" style to the div elements-container.

**Comment by CaptainMad** [comment]
By the way, I can't get the $.ajax running to save new position.
I put it there line 253 :
      if (hoveredElementIndex < dragElementIndex) {
        $(hoveredElement).before($dragElement);
        $.ajax({ url: 'MyProg.php',
            data: {positions: 'iconswap|' + hoveredElement.id + '|' + $dragElement[0].id},
            type: 'get'
            });
...
Any idea ?

**Comment by CaptainMad** [comment]
of course Ids are appropriately populated...
the call is not performed to MyProg ... why ?

**Comment by vishalok12** [comment]
Hi @CaptainMad, Sorry for my late response first.
Have you solved your issue?

It seems, might be you're getting an error in your ajax call. It would be best to debug your code to clearly find the mistake.
